//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpNL.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpNL.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _new {
            get {
                object obj = ResourceManager.GetObject("new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to close SharpNL.Gui?.
        /// </summary>
        internal static string ApplicationExit {
            get {
                return ResourceManager.GetString("ApplicationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string ApplicationExitTitle {
            get {
                return ResourceManager.GetString("ApplicationExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_out {
            get {
                object obj = ResourceManager.GetObject("arrow_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap avatarMrBean {
            get {
                object obj = ResourceManager.GetObject("avatarMrBean", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap brick {
            get {
                object obj = ResourceManager.GetObject("brick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap brick_go {
            get {
                object obj = ResourceManager.GetObject("brick_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Select the data file....
        /// </summary>
        internal static string btnSentData_Select {
            get {
                return ResourceManager.GetString("btnSentData_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chart_curve {
            get {
                object obj = ResourceManager.GetObject("chart_curve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap computer {
            get {
                object obj = ResourceManager.GetObject("computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap computer_go {
            get {
                object obj = ResourceManager.GetObject("computer_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cup {
            get {
                object obj = ResourceManager.GetObject("cup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document {
            get {
                object obj = ResourceManager.GetObject("document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit_32x32 {
            get {
                object obj = ResourceManager.GetObject("Edit_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task node {0} was ignored in the project because it is not recognized by the GUI..
        /// </summary>
        internal static string ErrorUnknownTask {
            get {
                return ResourceManager.GetString("ErrorUnknownTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_page {
            get {
                object obj = ResourceManager.GetObject("folder_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_wrench {
            get {
                object obj = ResourceManager.GetObject("folder_wrench", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap github {
            get {
                object obj = ResourceManager.GetObject("github", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heart {
            get {
                object obj = ResourceManager.GetObject("heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to af Afrikaans
        ///af-ZA Afrikaans (South Africa)
        ///ar Arabic
        ///ar-AE Arabic (U.A.E.)
        ///ar-BH Arabic (Bahrain)
        ///ar-DZ Arabic (Algeria)
        ///ar-EG Arabic (Egypt)
        ///ar-IQ Arabic (Iraq)
        ///ar-JO Arabic (Jordan)
        ///ar-KW Arabic (Kuwait)
        ///ar-LB Arabic (Lebanon)
        ///ar-LY Arabic (Libya)
        ///ar-MA Arabic (Morocco)
        ///ar-OM Arabic (Oman)
        ///ar-QA Arabic (Qatar)
        ///ar-SA Arabic (Saudi Arabia)
        ///ar-SY Arabic (Syria)
        ///ar-TN Arabic (Tunisia)
        ///ar-YE Arabic (Yemen)
        ///az Azeri (Latin)
        ///az-AZ Azeri (Latin) (Azerbaijan)
        ///az-AZ Azeri (Cyrillic) (Azerbaija [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        internal static string MessageTitleRequired {
            get {
                return ResourceManager.GetString("MessageTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oszillograph {
            get {
                object obj = ResourceManager.GetObject("oszillograph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page {
            get {
                object obj = ResourceManager.GetObject("page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_save {
            get {
                object obj = ResourceManager.GetObject("page_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_white_go {
            get {
                object obj = ResourceManager.GetObject("page_white_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paypal {
            get {
                object obj = ResourceManager.GetObject("paypal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a model.
        /// </summary>
        internal static string ProjectMenuModelAdd {
            get {
                return ResourceManager.GetString("ProjectMenuModelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenNLP Model (*.bin) |*.bin.
        /// </summary>
        internal static string ProjectMenuModelAddFilter {
            get {
                return ResourceManager.GetString("ProjectMenuModelAddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project already has a model of this type with the same language..
        /// </summary>
        internal static string ProjectMenuModelAddSame {
            get {
                return ResourceManager.GetString("ProjectMenuModelAddSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string ProjectMenuModelAddSameTitle {
            get {
                return ResourceManager.GetString("ProjectMenuModelAddSameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown model type :(.
        /// </summary>
        internal static string ProjectMenuModelAddUnknown {
            get {
                return ResourceManager.GetString("ProjectMenuModelAddUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported.
        /// </summary>
        internal static string ProjectMenuModelAddUnknownTitle {
            get {
                return ResourceManager.GetString("ProjectMenuModelAddUnknownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        internal static string ProjectModels {
            get {
                return ResourceManager.GetString("ProjectModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognize entities.
        /// </summary>
        internal static string ProjectNodeEntityRecognize {
            get {
                return ResourceManager.GetString("ProjectNodeEntityRecognize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes.
        /// </summary>
        internal static string ProjectNodeNodes {
            get {
                return ResourceManager.GetString("ProjectNodeNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        internal static string ProjectNodeOutputs {
            get {
                return ResourceManager.GetString("ProjectNodeOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string ProjectNodeTasks {
            get {
                return ResourceManager.GetString("ProjectNodeTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file.
        /// </summary>
        internal static string ProjectNodeTextFile {
            get {
                return ResourceManager.GetString("ProjectNodeTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text input.
        /// </summary>
        internal static string ProjectNodeTextInput {
            get {
                return ResourceManager.GetString("ProjectNodeTextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Input.
        /// </summary>
        internal static string ProjectNodeTrainInput {
            get {
                return ResourceManager.GetString("ProjectNodeTrainInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebGet.
        /// </summary>
        internal static string ProjectNodeWebGet {
            get {
                return ResourceManager.GetString("ProjectNodeWebGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the specified project file..
        /// </summary>
        internal static string ProjectOpenError {
            get {
                return ResourceManager.GetString("ProjectOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunk.
        /// </summary>
        internal static string ProjectTaskChunk {
            get {
                return ResourceManager.GetString("ProjectTaskChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse.
        /// </summary>
        internal static string ProjectTaskParse {
            get {
                return ResourceManager.GetString("ProjectTaskParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagger.
        /// </summary>
        internal static string ProjectTaskPOSTag {
            get {
                return ResourceManager.GetString("ProjectTaskPOSTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Model File.
        /// </summary>
        internal static string ProjectTaskSaveModelFile {
            get {
                return ResourceManager.GetString("ProjectTaskSaveModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect sentences.
        /// </summary>
        internal static string ProjectTaskSD {
            get {
                return ResourceManager.GetString("ProjectTaskSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train SD Model.
        /// </summary>
        internal static string ProjectTaskSDTrain {
            get {
                return ResourceManager.GetString("ProjectTaskSDTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokenize.
        /// </summary>
        internal static string ProjectTaskTokenize {
            get {
                return ResourceManager.GetString("ProjectTaskTokenize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Tokenizer Model.
        /// </summary>
        internal static string ProjectTaskTokenizeTrain {
            get {
                return ResourceManager.GetString("ProjectTaskTokenizeTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unamed project.
        /// </summary>
        internal static string ProjectUnamed {
            get {
                return ResourceManager.GetString("ProjectUnamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rainbow {
            get {
                object obj = ResourceManager.GetObject("rainbow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data file is required!.
        /// </summary>
        internal static string RequiredInputData {
            get {
                return ResourceManager.GetString("RequiredInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sitemap_color {
            get {
                object obj = ResourceManager.GetObject("sitemap_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_align_justify {
            get {
                object obj = ResourceManager.GetObject("text_align_justify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_allcaps {
            get {
                object obj = ResourceManager.GetObject("text_allcaps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_dropcaps {
            get {
                object obj = ResourceManager.GetObject("text_dropcaps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_horizontalrule {
            get {
                object obj = ResourceManager.GetObject("text_horizontalrule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_signature {
            get {
                object obj = ResourceManager.GetObject("text_signature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_uppercase {
            get {
                object obj = ResourceManager.GetObject("text_uppercase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap timeline_marker {
            get {
                object obj = ResourceManager.GetObject("timeline_marker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap world {
            get {
                object obj = ResourceManager.GetObject("world", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom {
            get {
                object obj = ResourceManager.GetObject("zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
